tasks:
  # - name: yolo_finetune_custom_lr_scheduler_four_phases_with_clipping
  #   git_checkout_target: yolo_architecture
  #   run: |
  #     python train_yolo.py --run_name yolo_finetune_custom_lr_scheduler_four_phases_with_clipping --continue_from_image_net_checkpoint_signature IM-122:checkpoints/epoch_14 --num_epochs 135 --batch_size 64 --lr_scheduler custom --lr 0.0001 --dropout 0.5 --device cuda --checkpoint_interval 10
  
  # good but overfitting
  # - name: yolo_finetune_fixed_lr_with_0.0001_lr
  #   git_checkout_target: yolo_architecture
  #   run: |
  #     python train_yolo.py --run_name yolo_finetune_fixed_lr_with_0.0001_lr --continue_from_image_net_checkpoint_signature IM-122:checkpoints/epoch_14 --num_epochs 135 --batch_size 64 --lr_scheduler fixed --lr 0.0001 --dropout 0.5 --device cuda --checkpoint_interval 10
  
  # - name: yolo_finetune_fixed_lr_with_0.001_lr_with_0.5_dropout_and_no_rotations_and_flips
  #   git_checkout_target: yolo_architecture
  #   run: |
  #     python train_yolo.py --run_name yolo_finetune_fixed_lr_with_0.001_lr_with_0.5_dropout_and_no_rotations_and_flips --continue_from_image_net_checkpoint_signature IM-122:checkpoints/epoch_14 --num_epochs 67 --batch_size 64 --lr_scheduler fixed --lr 0.001 --dropout 0.5 --device cuda --checkpoint_interval 5

  # - name: continue_yolo_finetune_fixed_lr_with_0.0001_lr_with_0.5_dropout_and_no_rotations_and_flips
  #   git_checkout_target: yolo_architecture
  #   run: |
  #     python train_yolo.py --run_name continue_yolo_finetune_fixed_lr_with_0.0001_lr_with_0.5_dropout_and_no_rotations_and_flips --continue_from_yolo_checkpoint_signature IM-230:checkpoints/epoch_10 --num_epochs 125 --batch_size 64 --lr_scheduler fixed --lr 0.0001 --dropout 0.5 --device cuda --checkpoint_interval 5

  - name: continue_with_0.00001_lr_from_IM_231_epoch_50
    git_checkout_target: yolo_architecture
    run: |
      python train_yolo.py --run_name continue_with_0.00001_lr_from_IM_231_epoch_50 --continue_from_yolo_checkpoint_signature IM-231:checkpoints/epoch_50 --num_epochs 75 --batch_size 64 --lr_scheduler fixed --lr 0.00001 --dropout 0.5 --device cuda --checkpoint_interval 5

  
